# Generated by Django 4.2.5 on 2023-09-15 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fileSystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvfile',
            name='count_rows',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='csvfile',
            name='size',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='CSVFileColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fileSystem.csvfile')),
            ],
        ),
    ]
